apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: replicaset
        labels:
                env: dev

spec:
        replicas: 3
        selector:

                matchExpressions:
                        
                       - key: app
                         operator: In
                         values:
                                 - app1


                       - key: env
                         operator: NotIn
                         values:
                                 - test


        template:
          metadata:
                name: firstpod
                labels:
                        app: app1
          spec:
                        containers:
                                - name: nginxpod
                                  image: nginx
