apiVersion: v1
kind: ReplicationController
metadata:
        name: rc
        labels:
                type: app

spec:
        replicas: 2
        template:

                metadata:
                        name: first_pod
                        labels:
                                env: dev
                spec:
                        containers:
                                - name: mysql 
                                  image: mysql 
                                  
