apiVersion: v1
kind: Pod
metadata:
        name: mysecondpod
        labels:
                env: test
                app: app1



spec:
        containers:
                - name: nginxtest
                  image: nginx

