apiVersion: v1
kind: Pod
metadata:
        name: db
        labels:
                env: test

spec:
        containers:
                - name: db-mysql
                  image: mysql
                  env:
                         - name: MYSQL_ROOT_PASSWORD
                           value: root123

                         - name: MYSQL_DATABASE
                           value: app_db

                         - name: MYSQL_USER
                           value: db_user

                         - name: MYSQL_PASSWORD
                           value: db_user_pass
