apiVersion: v1
kind: Service
metadata:
        name: nodeportservice
        labels:
                app: frontendapp


spec:
        type: NodePort
        ports:
                - targetPort: 80
                  port: 80
                  nodePort: 30008
        selector:
                app: frontendapp
                env: dev
