apiVersion: v1
kind: Service
metadata:
        name: profilecardservice
        labels:
                env: dev

spec:
         type: NodePort
         ports:
                 - targetPort: 80
                   port: 80
                   nodePort: 30008
         selector:
                 app: app1
          
