apiVersion: v1
kind: Pod
metadata:
        name: wordpress
        labels:
                env: test
                app: web

spec:
        containers:
                - name: wordpress
                  image: wordpress
                  env:
                          - name: WORDPRESS_DB_HOST
                            value: 10.244.1.10

                          - name: WORDPRESS_DB_USER
                            value: db_user

                          - name: WORDPRESS_DB_PASSWORD
                            value: db_user_pass

                          - name: WORDPRESS_DB_NAME
                            value: app_db
