apiVersion: v1
kind: Service
metadata:
        name: wordpressservice
        labels: 
                env: test

spec:
        type: NodePort
        ports:
                - targetPort: 80
                  port: 80
                  nodePort: 30008
        selector:
                env: test
                app: web
